### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by naviyakothari** [ORIE4741/ProjectsFall2019#105]
I’m reviewing a project that aims to explore the factors that affect the price of Airbnb stays in New York City. Their dataset comprises foundational data points from the Airbnb platform like location, room type, price, etc. and the team plans to interweave crime rate, additional utilities around location, etc. to enhance the analysis. This is with the intention to support homeowners with their pricing decisions as well as enable customers to gauge the reasonable price range for rent. 

The proposal is clear-cut, concise, and applicable to a large customer base. The basic features can provide good runway to test data analysis skills and output findings that are easy to comprehend. The problem could be a little hackneyed because of the breadth of research already done on Airbnb prices. Maybe implementing the complexities/less explored variables at the beginning itself could be interesting. You can also tie in hotel pricing + demand data and compare the effects of Airbnb’s growth on the tourism/stay industry. Also, visualizations for locations around NYC can provide good insight into the pricey areas, more in-demand areas, etc. As another dimension, perhaps analyzing customer reviews/sentiments for certain types of houses in certain locations could provide new findings.

**Comment by leonliyangdu** [comment]
Hospital Analysis: This project is about predicting the hospital choice of patients given their basic information, researching the correlation between the length of stay and the level of severity, and researching if certain medical facilities receive predominately number of patients with similar disease. They are using the data sets provided by Statewide Planning and Research Cooperative System and the Medical Expenditure Panel Survey and Practice Fusion. Their objective is a model that predicts the hospital choice given the patients’ basic information, and the researching results of the last two questions. 
I like the project in that: 1. the topic is very useful in real life and can bring good to our life; 2. the data sets they are using is really “big” data (2.54 million times 34 features) which accords with the course topic: dealing with big data; 3. the features are so diversified and plenty that I believe the predicting result should be good.
Three areas for improvement: 1. could be more precise if listing how to combine the three data sest; 2. can introduce the effect of the treat and incorporate it into the hosipital to use as the predicting label instead of just using the hospital as the predicting label, because people might have biases: even the hospital does not give the best treatment, they still tend to choose this hospital, but your goal is to give a “best” choice, not a “most frequent” choice; 3. coule be more precise if specifying what techniques to use to deal with big and messy data.

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.
